name: Build and Validate Artifact
description: Reusable action to build and validate the component artifact
runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: 20
