name: Build and Validate Artifact
description: Reusable action to build and validate the component artifact
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        ref: ${{ github.sha }}
    - name: Setup workspace
      uses: "./.github/actions/bootstrap"
    - name: Build & Validate Artifact
      id: build-validate-artifact
      run: |
        cd utils && yarn build-validate-quickstart-artifact
