name: Build and Validate Artifact
description: Reusable action to build and validate the component artifact
runs:
  using: composite
  steps:
    - name: Setup workspace
      uses: "./.github/actions/bootstrap"
    - name: Build & Validate Artifact
      shell: bash
      id: build-validate-artifact
      run: |
        cd utils && yarn build-validate-quickstart-artifact
