#  This workflow runs when a tag is created with the `v` prefix.
#  It runs our validation script, outputs the artifact, creates a Github
#  release, and uploads and associates the artifact with the release.

name: Release artifact
on:
  workflow_call:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.ref }}
      - name: Setup workspace
        uses: "./.github/actions/bootstrap"
      - name: Validate PR Artifact
        uses: "./.github/actions/build-validate-artifact"
        with:
          command-args: '--output-artifact'
      - name: Debugging output
        run: ls -la utils/build
      - name: Create release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        with:
          files: utils/build/*
          fail_on_unmatched_files: true
          make_latest: true
