name: Validate PR Artifact

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.sha }}
      - name: Setup workspace
        uses: "./.github/actions/bootstrap"
      - name: Validate PR Artifact
        uses: "./.github/actions/build-validate-artifact"
  create-release:
    needs: validate
    runs-on: ubuntu-latest
    # if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.sha }}
      - name: Create new release tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          tag_prefix: v
          create_annotated_tag: true
      - name: Publish release
        uses: "./.github/workflows/release-artifact.yml"
